apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: MCPRoute
metadata:
  name: mcp-route
  namespace: atlassian
spec:
  parentRefs:
    - name: ai-gateway
      namespace: default
      kind: Gateway
      group: gateway.networking.k8s.io

  path: "/mcp/atlassian"

  backendRefs:
    - name: atlassian
      kind: Backend
      group: gateway.envoyproxy.io
      path: "/v1/mcp"
      securityPolicy:
        apiKey:
          header: Authorization
          secretRef:
            name: atlassian-token

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: atlassian
  namespace: atlassian
spec:
  endpoints:
    - fqdn:
        hostname: mcp.atlassian.com
        port: 443
  type: Endpoints

---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: atlassian-tls
  namespace: atlassian
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: atlassian
  validation:
    wellKnownCACertificates: "System"
    hostname: mcp.atlassian.com