apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: MCPRoute
metadata:
  name: b-mcp-route
  namespace: brave-search
spec:
  parentRefs:
    - name: ai-gateway
      namespace: default
      kind: Gateway
      group: gateway.networking.k8s.io

  path: "/mcp/brave"

  backendRefs:
    - name: brave-search
      kind: Backend
      group: gateway.envoyproxy.io
      path: "/mcp"
      securityPolicy:
        apiKey:
          secretRef:
            name: brave-search-token
          header: X-API-Key


---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: brave-search
  namespace: brave-search
spec:
  endpoints:
    - fqdn:
        hostname: brave-search.brave-search.svc.cluster.local
        port: 8080
