apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: MCPRoute
metadata:
  name: context7-mcp-route
  namespace: converse-mcp
spec:
  parentRefs:
    - name: ai-gateway
      namespace: converse-llm
      kind: Gateway
      group: gateway.networking.k8s.io

  path: "/mcp/context7"

  backendRefs:
    - name: context7
      kind: Backend
      group: gateway.envoyproxy.io
      path: "/mcp"
      securityPolicy:
        apiKey:
          secretRef:
            name: context7-token

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: context7
  namespace: converse-mcp
spec:
  endpoints:
    - fqdn:
        hostname: mcp.context7.com
        port: 443

---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: context7-tls
  namespace: converse-mcp
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: context7
  validation:
    wellKnownCACertificates: "System"
    hostname: mcp.context7.com
