apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: MCPRoute
metadata:
  name: firecrawl-mcp-route
  namespace: converse-mcp
spec:
  parentRefs:
    - name: ai-gateway
      namespace: converse-llm
      kind: Gateway
      group: gateway.networking.k8s.io

  path: "/mcp/firecrawl"

  backendRefs:
    - name: fire-crawl
      kind: Backend
      group: gateway.envoyproxy.io
      path: "/v2/mcp"
      securityPolicy:
        apiKey:
          secretRef:
            name: firecrawl-token
          header: Authorization

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: fire-crawl
  namespace: converse-mcp
spec:
  endpoints:
    - fqdn:
        hostname: mcp.firecrawl.dev
        port: 443

---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: fire-crawl-tls
  namespace: converse-mcp
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: fire-crawl
  validation:
    wellKnownCACertificates: "System"
    hostname: mcp.firecrawl.dev
