apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: MCPRoute
metadata:
  name: kubernetes-mcp-route
  namespace: kubernetes
spec:
  parentRefs:
    - name: ai-gateway
      namespace: default
      kind: Gateway
      group: gateway.networking.k8s.io

  path: "/mcp/kubernetes"

  backendRefs:
    - name: kubernetes-mcp
      kind: Backend
      group: gateway.envoyproxy.io
      path: "/mcp"
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: kubernetes-mcp
  namespace: kubernetes
spec:
  endpoints:
    - fqdn:
        hostname: kubernetes-mcp.kubernetes.svc.cluster.local
        port: 8080