apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: MCPRoute
metadata:
  name: qdrant-mcp-route
  namespace: converse-mcp
spec:
  parentRefs:
    - name: ai-gateway
      namespace: default
      kind: Gateway
      group: gateway.networking.k8s.io

  path: "/mcp/qdrant"

  backendRefs:
    - name: qdrant-mcp
      kind: Backend
      group: gateway.envoyproxy.io
      path: "/mcp"

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: qdrant-mcp
  namespace: converse-mcp
spec:
  endpoints:
    - fqdn:
        hostname: qdrant-mcp.qdrant.svc.cluster.local
        port: 8080
