apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: MCPRoute
metadata:
  name: terraform-mcp-route
  namespace: converse-mcp
spec:
  parentRefs:
    - name: ai-gateway
      namespace: converse-llm
      kind: Gateway
      group: gateway.networking.k8s.io

  path: "/mcp/terraform"

  backendRefs:
    - name: terraform-mcp
      kind: Backend
      group: gateway.envoyproxy.io
      path: "/mcp"

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: terraform-mcp
  namespace: converse-mcp
spec:
  endpoints:
    - fqdn:
        hostname: terraform-mcp.converse-mcp.svc.cluster.local
        port: 8080
