apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: ai-gateway-v2
  namespace: converse-llm
spec:
  provider:
    type: Kubernetes
  telemetry:
    metrics:
      prometheus: {}
