apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: converse-authorino-security-policy-v2
  namespace: converse-llm
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: ai-gateway-v2
  extAuth:
    grpc:
      backendRefs:
      - group: ""
        kind: Service
        name: converse-authorino-authorization
        namespace: converse-llm
        port: 50051
        weight: 1
    failOpen: false
