apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: converse
  namespace: converse-llm
spec:
  logLevel: debug
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
  volumes:
    items:
    - name: lightbridge-ca
      mountPath: /etc/pki/tls/certs
      secrets:
      - authz-tls
      items:
      - key: ca.crt
        path: lightbridge-ca.crt
