apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: converse
  namespace: converse-llm
spec:
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
  volumes:
    items:
    - name: lightbridge-ca
      secret:
        secretName: authz-tls # You'll need to sync/copy this secret to converse-llm namespace
    mounts:
    - name: lightbridge-ca
      mountPath: /etc/pki/tls/certs/lightbridge-ca.crt
      subPath: ca.crt