apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: MCPRoute
metadata:
  name: f-mcp-route
  namespace: fire-crawl
spec:
  parentRefs:
    - name: ai-gateway
      namespace: default
      kind: Gateway
      group: gateway.networking.k8s.io

  path: "/mcp/firecrawl"

  backendRefs:
    - name: fire-crawl
      kind: Backend
      group: gateway.envoyproxy.io
      path: "/fc-74ac7da5d84f441e945b5c2f95371448/v2/mcp"

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: fire-crawl
  namespace: fire-crawl
spec:
  endpoints:
    - fqdn:
        hostname: mcp.firecrawl.dev
        port: 443

---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: fire-crawl-tls
  namespace: fire-crawl
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: fire-crawl
  validation:
    wellKnownCACertificates: "System"
    hostname: mcp.firecrawl.dev