resources:
  - context7-mcp.yaml
  - brave-search-deployment.yaml
  - brave-search-mcp.yaml
  - firecrawl-mcp.yaml
  - atlassian-mcp.yaml
  - kubernetes-mcp-deployment.yaml
  - kubernetes-mcp.yaml
  - qdrant-deployment.yaml
  - qdrant-mcp-deployment.yaml
  - qdrant-mcp.yaml
  - tavily-mcp.yaml
  - terraform-mcp-deployment.yaml
  - terraform-mcp.yaml