---
apiVersion: v1
kind: Namespace
metadata:
  name: atlassian
---
apiVersion: v1
kind: Namespace
metadata:
  name: brave-search
---
apiVersion: v1
kind: Namespace
metadata:
  name: browserless
---
apiVersion: v1
kind: Namespace
metadata:
  name: context7
---
apiVersion: v1
kind: Namespace
metadata:
  name: fire-crawl
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: playwright
---
apiVersion: v1
kind: Namespace
metadata:
  name: puppeteer
---
apiVersion: v1
kind: Namespace
metadata:
  name: qdrant
---
apiVersion: v1
kind: Namespace
metadata:
  name: tavily
---
apiVersion: v1
kind: Namespace
metadata:
  name: terraform
